sudo: false

language: node_js

env:
  global:
    - PORT=3000
matrix:
  include:
    - node_js: iojs-v1
    - node_js: iojs-v2
    - node_js: "0.10"
    - node_js: "0.12"

before_script:
  - "export DISPLAY=:99.0"
  - "node ./test/mock/server.js"
  - sleep 3 # give Web server some time to bind to sockets, etc

after_script: "npm install coveralls && cat ./coverage/lcov.info | coveralls && rm -rf ./coverage"
notifications:
  email:
    - tormozz48@gmail.com
    - yndx.tavria@yandex.ru
